updated documentation pages: Careful!!
SPARCED/SPARCED pull request #17
Opened 2024-12-06 23:29 UTC by JonahRileyHuggins

I did quite a bit of updating to reflect the use of a command line tool and urged users to only install the docker or singularity container unless looking to develop. I'd caution for a thorough look at the installation guide and verify that this is an appropriate level of modification.

2024-12-10 10:33 UTC, ChocolateCharlie commented
There seems to be way more changes in the build than in the source, which seems weird. Are you adding some files into the build directory by hand?

2024-12-10 10:46 UTC, ChocolateCharlie commented
So the command line installation guide would override the dev installation guide? Although I definitely agree on splitting documentation for the two different types of users, I think we should discuss further on how we plan things to look like, as we did when we restructured SPARCED and drew the files organization on Marc's board.

2024-12-10 15:44 UTC, JonahRileyHuggins commented
> There seems to be way more changes in the build than in the source, which seems weird. Are you adding some files into the build directory by hand?

Nope, could be something to do with my process? After updating an rst/md file, I rebuild via 
`sphinx-build -b html ./source ./build`
from within the `SPARCED/docs/` directory. Is this the same process you use?

2024-12-10 15:46 UTC, JonahRileyHuggins commented
> So the command line installation guide would override the dev installation guide? Although I definitely agree on splitting documentation for the two different types of users, I think we should discuss further on how we plan things to look like, as we did when we restructured SPARCED and drew the files organization on Marc's board.

That's a good point. The documentation needs to be more organized than me just making changes willy-nilly. For now, I'll just keep writing pages and adding them, rather than deleting anything. 

As far as this push, let me know whether you'd like to reject and I'll plan accordingly.

2024-12-11 09:54 UTC, ChocolateCharlie requested changes
Check comments for files `conf.py` and `installation-guide,md`.

2024-12-11 09:54 UTC, ChocolateCharlie commented on docs/source/conf.py
@JonahRileyHuggins I am confused on those paths

2024-12-11 09:54 UTC, ChocolateCharlie commented on docs/source/installation-guide.md
@JonahRileyHuggins could you split this into two separate files, one for modelers and one for developers? Except for a few editions, I still use my guide and it tends to work. I understand it is super verbose though, as a dev wouldn't need that many explanations while a modeler wouldn't install SPARCED that way anymore. Yet, it wouldn't hurt to keep it online, especially because the SPARCED-tools are not available on the main branch yet, so I think it's a little bit premature. Do you agree?

2024-12-11 09:58 UTC, ChocolateCharlie commented
Yeah, I'm not sure of what's going on with the build so let's say we close our eyes on thos files this time as long as it shows up correctly. I think we could accept but documentation should mostly explain how to use the code on the main branch.

2025-01-05 17:52 UTC, closed without merging

2025-01-05 17:52 UTC, JonahRileyHuggins commented
I've got more updates to make and I need to comply with the current RTD build process. I'll rework it and submit a new merge eventually.